services:
  memocho:
    container_name: memocho
    image: git.yaji.dev/sitischu/memocho
    restart: unless-stopped

    depends_on:
      mongodb:
        condition: service_started

    networks:
      - traefik
      - mongodb

    env_file:
      - .env

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memocho.rule=Host(`bin.example.com`)"


  mongodb:
    restart: unless-stopped
    image: mongo
    container_name: memocho-mongodb
    networks:
      - mongodb

    volumes:
      # Change this
      - /data/db:/data/db

networks:
  mongodb:
    name: mongodb
  traefik:
    external: true

